### ISSUE TITLE
Unable to inspect due to page is loading while opening with browser

### ISSUE THREAD

**Issue by rgupta7888** [mykola-mokhnach/Appium-iOS-Inspector#28]
Hi ,
I am trying to inspect something on the iOS device but while opening the Appium-iOS-Inspector with the browsers ( Chrome / Firefox / Safari ), unable to do that because the page is loading in doing so.
Actually, the page is loading fine for other screens but the issue is only with a listing screen where the screen has product list.
Please help

**Comment by danhitsgu** [comment]
Hi there,
Your problem is same with me, https://github.com/mykola-mokhnach/Appium-iOS-Inspector/issues/29
I think it is conflict between iOS 11 with appium, so in my idea, we should use another device with iOS 10.3, using Xcode 8, get indicator follow https://github.com/facebook/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance
then use this indicator with script, run it with iOS 11 device with Xcode latest.
i'm just try and success, but it spend more time doing that

**Comment by mykola-mokhnach** [comment]
It is a problem with WDA itself, which takes a lot of time to generate the page source. This has been slightly improved in appium@beta
